# Generated by Django 4.2.6 on 2023-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_requestmodel_city_requestmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
