# Generated by Django 4.2.6 on 2023-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_requestmodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
